name: Deploy Resource Group Bicep

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep File
      run: |
        az deployment sub create \
          --location southafricanorth \
          --template-file rg.bicep \
          --parameters rgName=testing-env
